apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - name: web
      protocol: TCP
      port: 80
    - name: tool
      protocol: TCP
      port: 8080